//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HCC.rc
//
#define IDR_MANIFEST                    1
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HCC_DIALOG                  102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       130
#define IDD_ITEMDIALOG                  131
#define IDD_TECHDIALOG                  133
#define IDB_BITMAP1                     137
#define IDD_MAPDIALOG                   138
#define IDD_PLOTDIALOG                  140
#define IDD_CONSTRUCTIONDIALOG          141
#define IDD_OPTIONS                     143
#define IDD_OPTGENERAL                  144
#define IDI_ICON1                       147
#define IDB_TOOLBARFORM0                149
#define IDB_TOOLBARFORM1                150
#define IDB_TOOLBARTECH0                151
#define IDB_TOOLBARTECH1                152
#define IDD_CRAFTERSEARCHDIALOG         153
#define IDD_INPUTDIALOG                 155
#define IDR_FORMMENU                    156
#define IDR_TECHMENU                    157
#define IDD_COMPONENTDIALOG             158
#define IDD_LEVELDIALOG                 160
#define IDD_REPORTDIALOG                162
#define IDB_TOOLBARCOMP1                164
#define IDB_TOOLBARCOMP0                165
#define IDB_TOOLBARWIZARD1              166
#define IDB_TOOLBARCONSTRUCT0           167
#define IDB_TOOLBARCONSTRUCT1           168
#define IDB_TOOLBARMAP0                 169
#define IDB_TOOLBARMAP1                 170
#define IDB_TOOLBARPLOT0                171
#define IDB_TOOLBARPLOT1                172
#define IDB_TOOLBARPROFILE0             173
#define IDB_TOOLBARPROFILE1             174
#define IDB_TOOLBARREPORT0              175
#define IDB_TOOLBARREPORT1              176
#define IDB_TOOLBARWIZARD0              177
#define IDB_TOOLBARUPDATES1             178
#define IDB_TOOLBARSEARCH0              179
#define IDB_TOOLBARSEARCH1              180
#define IDB_TOOLBARUPDATES0             181
#define IDR_REPORTMENU                  184
#define IDR_COMPMENU                    185
#define IDR_BUILDMENU                   186
#define IDD_PROFILEDIALOG               188
#define IDD_PROFILE1DIALOG              190
#define IDD_PROFILE2DIALOG              191
#define IDD_PROFILE3DIALOG              193
#define IDR_PROFILEMENU                 200
#define IDD_UPDATEDIALOG                201
#define IDD_WIZARDPAGE1                 206
#define IDD_DIALOG1                     208
#define IDD_WIZARDDIALOG                209
#define IDD_WIZARDPAGE2                 210
#define IDD_WIZARDPAGE3                 211
#define IDD_SKILLDIALOG                 214
#define IDD_NEWPROFILEDIALOG            215
#define IDD_CACHEDIALOG                 217
#define IDD_ORDERDIALOG                 218
#define IDR_ORDERMENU                   219
#define IDB_TOOLBARORDERS0              220
#define IDB_TOOLBARORDERS1              221
#define IDR_UPDATEMENU                  225
#define IDR_OPTIONMENU                  227
#define IDD_INPUTLISTDIALOG             228
#define IDR_TOOLBARACCEL                229
#define IDB_BITMAP2                     230
#define IDC_TREE1                       1000
#define IDC_BUTTON1                     1001
#define IDC_BROWSEBUTTON                1001
#define IDC_HIGHERBUTTON                1001
#define IDC_NEWBUTTON                   1001
#define IDC_BUTTON2                     1002
#define IDC_LOWERBUTTON                 1002
#define IDC_BUTTON3                     1003
#define IDC_SLIDER1                     1004
#define IDC_BUTTON4                     1004
#define IDC_DELETEITEM                  1004
#define IDC_MSFLEXGRID1                 1005
#define IDC_BUTTON5                     1005
#define IDC_SKILLGRID                   1005
#define IDC_REPORTGRID                  1005
#define IDC_MSFLEXGRID2                 1006
#define IDC_TECHTIERGRID                1006
#define IDC_BUILDINFO                   1006
#define IDC_BUTTON6                     1006
#define IDC_RESOURCEGRID                1007
#define IDC_BUTTON7                     1007
#define IDC_MSFLEXGRID4                 1008
#define IDC_TECHCOMPONENTGRID           1008
#define IDC_BUTTON8                     1008
#define IDC_COMBO1                      1009
#define IDC_TECHFILTER                  1009
#define IDC_BUILDINGFILTER              1009
#define IDC_BUTTON9                     1009
#define IDC_ITEMINFO                    1009
#define IDC_NAMECOMBO                   1009
#define IDC_REPORTSTYLE                 1009
#define IDC_SERVERLIST                  1009
#define IDC_SCHOOLNAMECOMBO             1009
#define IDC_ICONSIZECOMBO               1009
#define IDC_INPUTCOMBO                  1009
#define IDC_REMOVETECH                  1010
#define IDC_MAPFILTER2                  1010
#define IDC_SHARDCOMBO                  1010
#define IDC_REPORTFORMAT                1010
#define IDC_RACECOMBO                   1010
#define IDC_FORMULATREE                 1011
#define IDC_MAPFILTER3                  1011
#define IDC_SCHOOLTYPECOMBO             1011
#define IDC_REPORTTYPE                  1011
#define IDC_FORMULAFILTER               1012
#define IDC_PROFILESCHOOLCOMBO          1012
#define IDC_TIERGRID                    1013
#define IDC_TECHGRID                    1014
#define IDC_ITEMINFOGRID                1015
#define IDC_ADDITEM                     1016
#define IDC_FILTERBUTTON                1017
#define IDC_SHOWLEVELS                  1017
#define IDC_PROFILESELECTER             1018
#define IDC_SIZINGBOX                   1019
#define IDC_SIZINGTITLEBOX              1020
#define IDC_ITEMSELECTER                1021
#define IDC_ADDTECH                     1024
#define IDC_TECHINFOGRID                1025
#define IDC_FILTERFORMS                 1026
#define IDC_BUILDTREE                   1027
#define IDC_ADDSTRUCTURE                1028
#define IDC_BUILDRESOURCES              1029
#define IDC_MAPFILTER1                  1030
#define IDC_MAP                         1031
#define IDC_MAPINFO                     1032
#define IDC_MAPSELECT                   1033
#define IDC_MAPNEXT                     1034
#define IDC_STRUCTURETREE               1035
#define IDC_REMOVESTRUCTURE             1036
#define IDC_PLOTIMAGE                   1037
#define IDC_STRUCTURELIST               1038
#define IDC_EDIT1                       1039
#define IDC_GAMEDIR                     1039
#define IDC_SCHOOLLEVEL                 1039
#define IDC_SKILLEDIT                   1039
#define IDC_TITLE                       1039
#define IDC_SKILLNAME                   1039
#define IDC_EDIT2                       1040
#define IDC_SHOWUSABLE                  1040
#define IDC_ICONSIZE                    1040
#define IDC_TESTEDIT                    1041
#define IDC_OPTIONTAB                   1042
#define IDC_TECHTREE                    1048
#define IDC_CHECK1                      1049
#define IDC_ICONCHECK                   1049
#define IDC_APPENDCHECK                 1049
#define IDC_AUTODOCK                    1049
#define IDC_CHECK2                      1050
#define IDC_CACHECHECK                  1050
#define IDC_HOTKEYCHECK                 1051
#define IDC_ITEMTREE                    1052
#define IDC_TOOLBARDRAGCHECK            1052
#define IDC_EDITITEM                    1053
#define IDC_PRIORITYCHECK               1053
#define IDC_COPYITEM                    1054
#define IDC_ITEMQTY                     1055
#define IDC_SUBMITREQUESTBUTTON         1055
#define IDC_ITEMTOTALQTY                1056
#define IDC_VIEWPROFILEBUTTON           1056
#define IDC_ITEMFRAME                   1057
#define IDC_ALIGNTIERS                  1057
#define IDC_QTYDESC                     1058
#define IDC_COPYTOCLIPBOARD             1058
#define IDC_FORMBUTTON                  1059
#define IDC_TECHBUTTON                  1060
#define IDC_SEARCHLIST                  1060
#define IDC_REPORTBUTTON                1061
#define IDC_SEARCHBUTTON                1061
#define IDC_CRAFTERSEARCH               1062
#define IDC_SEARCHFRAME                 1062
#define IDC_CREATEBUTTON                1062
#define IDC_TECHLIST                    1063
#define IDC_ORDERBUTTON                 1063
#define IDC_NEWGROUPBUTTON              1064
#define IDC_SUBMIT                      1064
#define IDC_ITEMNAME                    1065
#define IDC_INPUTMSG                    1066
#define IDC_REPORTBUTTON2               1066
#define IDC_WIZARDBUTTON                1066
#define IDC_INPUTEDIT                   1067
#define IDC_DELETEBUTTON                1067
#define IDC_ORDERFRAME                  1068
#define IDC_COPYBUTTON                  1068
#define IDC_ITEMPREVIEW                 1069
#define IDC_QTYSPIN                     1070
#define IDC_REPORTBUTTON3               1071
#define IDC_COMPFILTER                  1071
#define IDC_MAPBUTTON                   1071
#define IDC_REPORTBUTTON4               1072
#define IDC_COMPTREE                    1072
#define IDC_BUILDINGBUTTON              1072
#define IDC_REPORTBUTTON5               1073
#define IDC_FILTERTECHS                 1073
#define IDC_PROFILEBUTTON               1073
#define IDC_TIERFILTER                  1073
#define IDC_REPORTBUTTON6               1074
#define IDC_COMPINFOGRID                1074
#define IDC_PLOTBUTTON                  1074
#define IDC_REPORTBUTTON7               1075
#define IDC_UPDATEBUTTON                1075
#define IDC_REPORTBUTTON8               1076
#define IDC_COMPBUTTON                  1076
#define IDC_CLOSEBUTTON                 1076
#define IDC_RESOURCEFILTER              1078
#define IDC_GENERATEBUTTON              1079
#define IDC_REPORTFRAME                 1080
#define IDC_PROFILETREE                 1082
#define IDC_EMAIL                       1083
#define IDC_SERVERCOMBO                 1084
#define IDC_NAME                        1085
#define IDC_ADVENTURELIST               1094
#define IDC_STATISTICSLIST              1095
#define IDC_CRAFTLIST                   1096
#define IDC_OPTSCHOOLS                  1099
#define IDC_OPTSKILLS                   1100
#define IDC_UPDATE                      1100
#define IDC_PROFILETEXT                 1101
#define IDC_COLLAPSE                    1102
#define IDC_EXPAND                      1103
#define IDC_ITEMTEXT                    1104
#define IDC_ARCHIVELIST                 1105
#define IDC_STATUSPROGRESS              1108
#define IDC_STATUSPROGRESSTOTAL         1109
#define IDC_STATUSLIST                  1111
#define IDC_TOTALPROGRESS               1112
#define IDC_CURRENTPROGRESS             1113
#define IDC_CLIENTVERSION               1113
#define IDC_CURRENTFILE                 1114
#define IDC_ICONSIZESPIN                1115
#define IDC_REVISION                    1115
#define IDC_PROFILELIST                 1116
#define IDC_CURCLIENTVERSION            1116
#define IDC_OPTMANUAL                   1117
#define IDC_OPTPROFILE                  1118
#define IDC_SCHOOLLEVELSPIN             1120
#define IDC_INFO                        1121
#define IDC_CATEGORYTREE                1122
#define IDC_DESC                        1124
#define IDC_FILTERLIST                  1126
#define IDC_CATEGORIESTEXT              1127
#define IDC_FORMULASTEXT                1128
#define IDC_TOPTITLE                    1130
#define IDC_MSG                         1131
#define IDC_MINCLIENTTEXT               1132
#define IDC_CURCLIENTTEXT               1133
#define IDC_RESOURCELIST                1133
#define IDC_TECHSTEXT                   1134
#define IDC_TITLEFRAME                  1137
#define IDC_DATABASETITLE               1138
#define IDC_VERSIONCOMMENT              1139
#define IDC_CLIENTCOMMENT               1140
#define IDC_DOCKINGCOMBO                1144
#define IDC_THEMECOMBO                  1145
#define IDC_ORDERSHEADER                1146
#define IDC_DATABASEHEADER              1147
#define IDC_ONLINEHEADER                1148
#define IDC_COUNTLIST                   1149
#define IDC_AUTOUPDATECHECK             1150
#define ID_FILE_SAVEAS                  32774
#define ID_FILE_EXIT                    32775
#define ID_EDIT_DELETE                  32777
#define ID_VIEW_ITEMS                   32780
#define ID_VIEW_REPORTS_BYITEMS         32781
#define ID_VIEW_REPORTS_BYCOMPONENTS    32782
#define ID_VIEW_REPORTS_HTMLREPORT      32783
#define ID_VIEW_TRYOUTS_BIPED           32784
#define ID_VIEW_TRYOUTS_DRAGON          32785
#define ID_VIEW_PROFILES                32786
#define ID_VIEW_BONUSES                 32788
#define ID_VIEW_TECHNIQUES              32789
#define ID_VIEW_RESOURCES_LOCATIONS     32790
#define ID_VIEW_RESOURCES_COST          32791
#define ID_SETTINGS_OPTIONS             32792
#define ID_HELP_ABOUT                   32794
#define ID_BUTTON32795                  32795
#define ID_BUTTON32796                  32796
#define ID_VIEW_REPORTS                 32799
#define ID_VIEW_MAP                     32800
#define ID_VIEW_CONSTRUCTION            32801
#define ID_VIEW_PLOTLAYOUT              32803
#define ID_SETTINGS_FORMULAWINDOW_SNAPSHOTWINDOW 32810
#define ID_SETTINGS_FORMULAWINDOW_RESTOREDEFAULTS 32811
#define ID_SETTINGS_TECHNIQUEWINDOW_SNAPSHOTWINDOW 32812
#define ID_SETTINGS_TECHNIQUEWINDOW_RESTOREWINDOW 32813
#define ID_SETTINGS_ORDERWINDOW_SNAPSHOTWINDOW 32815
#define ID_SETTINGS_ORDERWINDOW_RESTOREDEFAULTS 32816
#define ID_SETTINGS_ALLWINDOWS_SNAPSHOTWINDOWS 32817
#define ID_SETTINGS_ALLWINDOWS_RESTOREALLDEFAULTS 32818
#define ID_SETTINGS_CONSTRUCTIONWINDOW_SNAPSHOTWINDOW 32823
#define ID_SETTINGS_CONSTRUCTIONWINDOW_RESTOREDEFAULTS 32824
#define ID_SETTINGS_PLOTWINDOW_SNAPSHOTWINDOW 32825
#define ID_SETTINGS_PLOTWINDOW_RESTOREDEFAULTS 32826
#define ID_SETTINGS_MAPWINDOW_SNAPSHOTWINDOW 32827
#define ID_SETTINGS_MAPWINDOW_RESTOREDEFAULTS 32828
#define ID_SETTINGS_REPORTWINDOW_SNAPSHOTWINDOW 32829
#define ID_SETTINGS_REPORTWINDOW_RESTOREDEFAULTS 32830
#define ID_FILE_SAVEPLOT                32831
#define ID_FILE_SAVEPLOTAS              32832
#define ID_OPTIONS_SNAPSHOTWINDOW       32833
#define ID_OPTIONS_RESTOREWINDOW        32834
#define ID_VIEW_COMPONENTS              32837
#define ID_OPTIONS_EXPANDRESOURCELIST   32838
#define ID_OPTIONS_REDUCERESOURCELIST   32839
#define ID_OPTIONS_DISPLAYLESSRESOURCE  32846
#define ID_OPTIONS_DISPLAYMORERESOURCE  32847
#define ID_OPTIONS_SETRESOURCEGRIDTO_4LINES 32849
#define ID_OPTIONS_SETRESOURCEGRIDTO_6LINES 32851
#define ID_OPTIONS_SETRESOURCEGRIDTO_10LINES 32852
#define ID_OPTIONS_SETRESOURCEGRIDTO_8LINES 32853
#define ID_OPTIONS_SETRESOURCEGRIDTO_12LINES 32854
#define ID_OPTIONS_SETRESOURCEGRIDTO_14LINES 32855
#define ID_SETTINGS_RELOADDATA          32856
#define ID_OPTIONS_SHOWSUBCOMPONENTS    32858
#define ID_OPTIONS_SHOWBASERESOURCE     32859
#define ID_OPTIONS_RESOURCEBREAKDOWN_SHOWFORMULARESOURCE 32860
#define ID_OPTIONS_ORDERBY_RESOURCETYPE 32861
#define ID_OPTIONS_ORDERBY_QUANTITY     32862
#define ID_WINDOW_SNAPSHOTWINDOW        32863
#define ID_WINDOW_RESTOREWINDOW         32864
#define ID_OPTIONS_AUTOEXPAND_OFF       32865
#define ID_OPTIONS_AUTOEXPAND_CURRENTCATEGORY 32866
#define ID_OPTIONS_AUTOEXPAND_ALLCATEGORIES 32867
#define ID_SELECTION_SELECTNONE         32868
#define ID_SELECTION_SELECTALL          32869
#define ID_SELECTION_INVERTSELECTION    32870
#define ID_SELECTION_COPYTOCLIPBOARD    32871
#define ID_SEARCH_BYNAME                32873
#define ID_SEARCH_BYCLASS               32874
#define ID_HELP_HELP                    32875
#define ID_SEARCH_BYFORMNAME            32876
#define ID_SETTINGS_TECHNIQUEWINDOW_RESTOREDEFAULTS 32877
#define ID_SETTINGS_COMPWINDOW_SNAPSHOTWINDOW 32878
#define ID_SETTINGS_COMPWINDOW_RESTOREDEFAULTS 32879
#define ID_SETTINGS_PROFILEWINDOW_SNAPSHOTWINDOW 32880
#define ID_SETTINGS_PROFILEWINDOW_RESTOREDEFAULTS 32881
#define ID_SETTINGS_BUILDINGWINDOW_SNAPSHOTWINDOW 32882
#define ID_SETTINGS_BUILDINGWINDOW_RESTOREDEFAULTS 32883
#define ID_OPTIONS_AUTOEDITITEMS        32884
#define ID_VIEW_FORMULAWINDOW           32885
#define ID_VIEW_TECHNIQUEWINDOW         32886
#define ID_VIEW_COMPONENTWINDOW         32887
#define ID_VIEW_REPORTWINDOW            32888
#define ID_VIEW_PROFILEWINDOW           32889
#define ID_VIEW_BUILDINGWINDOW          32890
#define ID_SETTINGS_WINDOW_TOOLBARWINDOW_SNAPSHOTWINDOW 32891
#define ID_SETTINGS_TOOLBARWINDOW_RESTOREDEFAULTS 32892
#define ID_SETTINGS_VIEW_ORDERWINDOW    32893
#define ID_WINDOW_ALWAYSONTOP           32894
#define ID_OPTIONS_RESOURCEGRID_UNLIMITED 32896
#define ID_OPTIONS_RESOURCEGRID_LIMITTO4ROWS 32897
#define ID_OPTIONS_RESOURCEGRID_LIMITTO8ROWS 32898
#define ID_OPTIONS_RESOURCEGRID_LIMITTO12ROWS 32899
#define ID_HELP_HELPWITHUPDATES         32902
#define ID_HELP_ONELINEMANUAL           32903
#define ID_HELP_REPORTABUG              32904
#define ID_OPTIONS_VIEW_LIVEUPDATE      32905
#define ID_OPTIONS_BONUSES_DIRECTONLY   32906
#define ID_OPTIONS_BONUSES_ALL          32907
#define ID_OPTIONS_SETTINGS_REFRESHTHEME 32908
#define ID_OPTIONS_ORIENTATION_VERTICAL 32909
#define ID_OPTIONS_ORIENTATION_HORIZONTAL 32910
#define ID_OPTIONS_RESOURCEGRID_AUTOSHRINK 32911
#define ID_HELP_PLUGINS                 32912

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        232
#define _APS_NEXT_COMMAND_VALUE         32913
#define _APS_NEXT_CONTROL_VALUE         1150
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
